# Generated by Django 5.0.1 on 2024-02-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_viz', '0002_alter_studentdata_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
