# Generated by Django 5.0.1 on 2024-02-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_viz', '0003_alter_studentdata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255, verbose_name='School Name')),
            ],
        ),
    ]
