# Generated by Django 5.0.1 on 2024-02-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_viz', '0004_schooldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answers', models.CharField(max_length=255, verbose_name='Answers')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAreaData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_areas', models.CharField(max_length=255, verbose_name='Assessment Areas')),
            ],
        ),
        migrations.CreateModel(
            name='AwardData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('award', models.CharField(max_length=255, verbose_name='Award')),
            ],
        ),
        migrations.CreateModel(
            name='ClassData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255, verbose_name='Class Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
            ],
        ),
    ]
